from __future__ import annotations

from typing import Protocol

from .models import CityEndpoint, CityIdentity, CityPresence, TrustLevel, TrustRecord


class CityRegistry(Protocol):
    def upsert_identity(self, identity: CityIdentity) -> None: ...
    def get_identity(self, city_id: str) -> CityIdentity | None: ...
    def list_identities(self) -> list[CityIdentity]: ...
    def upsert_endpoint(self, endpoint: CityEndpoint) -> None: ...
    def get_endpoint(self, city_id: str) -> CityEndpoint | None: ...


class DiscoveryService(Protocol):
    def announce(self, presence: CityPresence) -> None: ...
    def get_presence(self, city_id: str) -> CityPresence | None: ...
    def list_cities(self) -> list[CityPresence]: ...


class InternetRouter(Protocol):
    def resolve(self, source_city_id: str, target_city_id: str) -> CityEndpoint | None: ...


class TrustEngine(Protocol):
    def record(self, trust: TrustRecord) -> None: ...
    def evaluate(self, source_city_id: str, target_city_id: str) -> TrustLevel: ...


class FederationTransport(Protocol):
    def read_outbox(self) -> list[dict]: ...
    def append_to_inbox(self, messages: list[object]) -> int: ...
    def write_directive(self, directive: object, *, directive_id: str) -> None: ...
    def list_directives(self) -> list[dict]: ...
    def list_reports(self) -> list[dict]: ...
