from __future__ import annotations

from typing import Protocol

from .models import (
    CityEndpoint,
    CityIdentity,
    CityPresence,
    HostedEndpoint,
    LotusLinkAddress,
    LotusNetworkAddress,
    TrustLevel,
    TrustRecord,
)


class CityRegistry(Protocol):
    def upsert_identity(self, identity: CityIdentity) -> None: ...
    def get_identity(self, city_id: str) -> CityIdentity | None: ...
    def list_identities(self) -> list[CityIdentity]: ...
    def upsert_endpoint(self, endpoint: CityEndpoint) -> None: ...
    def get_endpoint(self, city_id: str) -> CityEndpoint | None: ...
    def list_endpoints(self) -> list[CityEndpoint]: ...
    def assign_link_address(self, city_id: str, *, ttl_s: float | None = None) -> LotusLinkAddress: ...
    def get_link_address(self, city_id: str) -> LotusLinkAddress | None: ...
    def list_link_addresses(self) -> list[LotusLinkAddress]: ...
    def assign_network_address(self, city_id: str, *, ttl_s: float | None = None) -> LotusNetworkAddress: ...
    def get_network_address(self, city_id: str) -> LotusNetworkAddress | None: ...
    def list_network_addresses(self) -> list[LotusNetworkAddress]: ...
    def upsert_hosted_endpoint(self, endpoint: HostedEndpoint) -> None: ...
    def get_hosted_endpoint(self, endpoint_id: str) -> HostedEndpoint | None: ...
    def get_hosted_endpoint_by_handle(self, public_handle: str, *, now: float | None = None) -> HostedEndpoint | None: ...
    def list_hosted_endpoints(self) -> list[HostedEndpoint]: ...


class DiscoveryService(Protocol):
    def announce(self, presence: CityPresence) -> None: ...
    def get_presence(self, city_id: str) -> CityPresence | None: ...
    def list_cities(self) -> list[CityPresence]: ...


class InternetRouter(Protocol):
    def resolve(self, source_city_id: str, target_city_id: str) -> CityEndpoint | None: ...
    def resolve_public_handle(self, public_handle: str, *, now: float | None = None) -> HostedEndpoint | None: ...


class TrustEngine(Protocol):
    def record(self, trust: TrustRecord) -> None: ...
    def evaluate(self, source_city_id: str, target_city_id: str) -> TrustLevel: ...


class FederationTransport(Protocol):
    def read_outbox(self) -> list[dict]: ...
    def append_to_inbox(self, messages: list[object]) -> int: ...
    def write_directive(self, directive: object, *, directive_id: str) -> None: ...
    def list_directives(self) -> list[dict]: ...
    def list_reports(self) -> list[dict]: ...
